### ISSUE TITLE
ldjson with fields list doesn't serialize JSON structures correctly.

### ISSUE THREAD

**Issue by kstaken** [terascope/file-assets#161]
The `file_exporter` does not correctly serialize fields that contain more complex JSON structures like objects or arrays.

```
{
    field: {
        subfield: "a",
        subfield: "b"
    }
}
```

would serialize as

```
{ field: {} }
```

In the report I received there was a field list involved but I'm not sure if that's the only case where it appears.

**Comment by macgyver603** [comment]
I was able to replicate the issue both with a record like above as well as an array field with an object as one of its elements. It looks like this is just a result of passing a populated `fields` opConfig parameter to [`JSON.stringify()`'s replacer parameter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#The_replacer_parameter), which will be recursively applied to all nested objects, so subfields need to be included in the `fields` list for the opConfig as well. It looks like order of the subfields is important for the parameter, but the subfields can be added anywhere in the `fields` list.

i.e. for this record:  
```
{
  field1: {
    subfield1: 22,
    subfield2: 44
  },
  field2: 66
}
```

Having `fields: ['field1', 'subfield1', 'subfield2', 'field2']` or `fields: ['field1', 'field2', 'subfield1', 'subfield2']` will both serialize as:  
```
{ field1: { subfield1: 22, subfield2:44 }, field2: 66 }
```

and having `fields: ['field1', 'subfield2', 'subfield1', 'field2']` or `fields: ['field1', 'field2', 'subfield2', 'subfield1']` will both serialize as:  
```
{ field1: { subfield2: 44, subfield1:22 }, field2: 66 }
```

I'll update the `fields` parameter description to include this information.

**Comment by macgyver603** [comment]
I've implemented a custom `_stringify()` for those cases in order to preserve the entire nested object no matter its internal structure. It will also preserve the order of the `fields` listed in the opConfig in the output.
