### ISSUE TITLE
Better error when s3 objects not found

### ISSUE THREAD

**Issue by godber** [terascope/file-assets#164]
I recently created a job that read from s3 something like this:

```
        {
            "_op": "s3_reader",
            "bucket": "myBucket",
            "connection": "s3",
            "size": 1000000,
            "format": "ldjson",
            "path": "/records.ldjson"
        },
```

This resulted in a `terminated` job with the following `_failureReason `:

```
"execution aa1032c1-4a72-41f4-8c19-4924036a2e79 received shutdown before the slicer could complete, setting status to \"terminated\"",
```

The error from the slicer logs is as follows:

```
  TypeError: Cannot read property 'Key' of undefined
    at S3Slicer.getObjects (/app/assets/93ca14ef05f7d4ee65d9d4b89430f2bef934a750/s3_reader/slicer.js:45:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Instead, the job should be `terminated` with a more instructive error.  Something that gives the user a clue as to why the problem occurred.  Something like

```
Slicer found zero objects in bucket: <BUCKET> with object_prefix: <OBJECT_PREFIX>
```

See https://github.com/terascope/file-assets/blob/v0.8.1/asset/s3_reader/slicer.js#L45 for context.

**Comment by godber** [comment]
@peterdemartini, @kstaken or @jsnoble should this sort of error be `failed` or `terminated`?

**Comment by kstaken** [comment]
should be failed
