### ISSUE TITLE
Convert file_reader to use DataEntities

### ISSUE THREAD

**Issue by godber** [terascope/file-assets#18]
The file_reader (and everything else probably later) should be converted to use DataEntities.

**Comment by godber** [comment]
It also needs to take a format option that, when set to `csv`, returns the csv string as a `.data` property on the dataentity.

**Comment by kstaken** [comment]
Format should be `raw` not `csv` which means it's splits the input into lines and then sticks that into a `data` attribute on the returned DataEntity. This should work for any line oriented txt based format and allows the next phase in the process to decode it.

**Comment by macgyver603** [comment]
This was addressed within the chunked file reader here: https://github.com/terascope/chunked-file-reader/pull/9
