### ISSUE TITLE
Fix file_reader memory leak

### ISSUE THREAD

**Issue by godber** [terascope/file-assets#21]
The file readers exhibit a very clear linear growth in worker memory usage which probably indicates the presence of a memory leak.  This should be tracked down and fixed.

<img width="612" alt="screen shot 2019-02-21 at 10 16 10 am" src="https://user-images.githubusercontent.com/1249/53188081-d4ffb980-35c1-11e9-9e45-e2e8ac4315f4.png">

**Comment by kstaken** [comment]
This was a phantom.
