### ISSUE TITLE
Cleanup / expand format support

### ISSUE THREAD

**Issue by kstaken** [terascope/file-assets#24]
In the docs it doesn't appear to clearly explain what formats are supported and some of the options only apply to a particular format which should be noted on those options.

Also we should be more specific with our usage of the term `json`. What we really mean by that is `ldjson` for `line delimited json`. So let's replace `json` with `ldjson` in all cases where line delimited json is the actual input/output format.

Then let's add `json` as an output and input format for the scenarios where it may make sense for that to exist. For instance on the file_exporter when `file_per_slice` is true then it would be possible to write the entire slice out as an actual JSON document that could then just be read and parsed.

This change from `json` to `ldjson` is technically a breaking change but we need to clean this up.

So our list of formats becomes

* csv
* tsv
* json
* ldjson
* raw

NOTE: I'm filing this ticket on the file_assets but I'd like to see this considered and made consistent everywhere that formats can be specified. This means that we should ask the question of what format can / should each operation support and this may affect some of the framework level serialization options in Teraslice it self.

**Comment by macgyver603** [comment]
Accidentally closed in the reference. I'm currently testing an upgrade for `file-assets` that uses that updated `chunked-file-reader` to take advantage of the additional formatting options.
